/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eindopdrachtherkansing;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import static jdk.nashorn.tools.ShellFunctions.input;

/**
 *
 * @author aditi
 */
public class GUI extends javax.swing.JFrame {
    private String pokemon;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pokemonLabel = new javax.swing.JLabel();
        pokeInput = new javax.swing.JTextField();
        kiesButton = new javax.swing.JButton();
        pokeOutput = new javax.swing.JLabel();
        bestandLabel = new javax.swing.JLabel();
        filePathField = new javax.swing.JTextField();
        bladerButton = new javax.swing.JButton();
        fileOpener = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        adviesLabel = new javax.swing.JLabel();
        setNameLabel = new javax.swing.JLabel();
        setAdviesLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        setIDLabel = new javax.swing.JLabel();
        baseXpProgressB = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        htPorgressB = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        weightProgressB = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        baseNr = new javax.swing.JLabel();
        heightNr = new javax.swing.JLabel();
        weightNr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pokemonLabel.setText("Pokémon");

        kiesButton.setText("kies");
        kiesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kiesButtonActionPerformed(evt);
            }
        });

        pokeOutput.setText("...");

        bestandLabel.setText("Bestand");

        bladerButton.setText("blader");
        bladerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bladerButtonActionPerformed(evt);
            }
        });

        fileOpener.setText("Open");
        fileOpener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileOpenerActionPerformed(evt);
            }
        });

        nameLabel.setText("Name:");

        idLabel.setText("ID:");

        adviesLabel.setText("Advies:");

        jLabel2.setText("Base XP");

        jLabel3.setText("Height");

        jLabel4.setText("Weight");

        baseNr.setText("jLabel5");

        heightNr.setText("jLabel5");

        weightNr.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                    .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(setIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(172, 172, 172))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pokemonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pokeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bestandLabel)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(filePathField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(setNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(29, 29, 29)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kiesButton)
                                .addGap(30, 30, 30)
                                .addComponent(pokeOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(adviesLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bladerButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(fileOpener))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(setAdviesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(weightProgressB, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(htPorgressB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(baseXpProgressB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(baseNr, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heightNr, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weightNr))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pokemonLabel)
                    .addComponent(pokeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kiesButton)
                    .addComponent(pokeOutput))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bestandLabel)
                    .addComponent(filePathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bladerButton)
                    .addComponent(fileOpener))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(setNameLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adviesLabel)
                            .addComponent(setAdviesLabel))))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(jLabel1)
                    .addComponent(setIDLabel))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(baseXpProgressB, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(baseNr))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(htPorgressB, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(heightNr))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weightProgressB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightNr))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bladerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bladerButtonActionPerformed
        // TODO add your handling code here:
        // BLADER BUTTON
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory()); // gets the file from the directory
        int returnValue = jfc.showOpenDialog(null); // shows the files in de Dialog
        
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile(); // gets the selected file
            System.out.println(selectedFile.getAbsolutePath()); // gets the absolute pathway of the file
            filePathField.setText(selectedFile.getAbsolutePath()); // shows the absolute pathway in the dialog system

            try {
               /**Java functie om een ";"- separated bestand te lezen door gebruik te maken van BufferedReader en String split () methode.
                * door de pokemondb.txt om te zetten naar een ArrayList is het mogelijk om het bestand ";"- separated in te lezen.
                */
               List pokemon = new ArrayList<>();
               BufferedReader br = new BufferedReader(new FileReader(selectedFile));
               String line = br.readLine(); // Leest de header en negeert het
               while ((line = br.readLine()) != null && !line.isEmpty()){
                  String[] fields = line.split(";");
                  String ID = fields[0];
                  setIDLabel.setText(fields[0]); // prints label ID
                  String Name = fields[1];
                  setNameLabel.setText(fields[1]); // prints label Name
                  String Species_ID = fields[2];
                  String Height = fields [3];
                  heightNr.setText(fields[3]); // prints original number from .txt file in label behinde de progressBar
                  String Weight = fields [4];
                  weightNr.setText(fields[4]); // prints original number from .txt file in label behinde de progressBar
                  String Base_XP = fields [5];
                  baseNr.setText(fields[5]); // prints original number from .txt file in label behinde de progressBar
                  String Order = fields [6];

                  
  
               }
               
                              
               /*
               Maakt één String van alle losse regels, de bedoeling is dat alles nu per regel wordt gelezen.
               */
               StringBuilder builder = new StringBuilder();
               String pokemon = "";
               while ((pokemon = br.readLine()) != null) {
                    builder.append(pokemon);
               }

                
                } catch (Exception e) {
                    e.printStackTrace();
                }
                
        }
    }//GEN-LAST:event_bladerButtonActionPerformed

    private void kiesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kiesButtonActionPerformed
        // TODO add your handling code here:
        /**
         * Met de "kies"- button, kies ik voor de pokemon uit het bestand pokemondb.txt.
         * Als ik in de invoerveld "pokemonInput" bulbasaur intype bijvoorbeeld, wordt het bevestigd door op de "kies"-knopje te drukken
         * dat bulbasaur gegevens voor gaan komen uit de pokemondb.txt. Als eerst wordt het bevestigd door het in de pokemonOutput (label) te zetten.
         */
        String pokemonInput = pokeInput.getText();
        pokeOutput.setText(pokemonInput);
        
        String selectedPokemon = null;
        this.pokemon = selectedPokemon;
        
    }//GEN-LAST:event_kiesButtonActionPerformed

    private void fileOpenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileOpenerActionPerformed
        // TODO add your handling code here:
        String getselectedPokemon = this.pokemon;
        
        /*
        De progressbars berekend en en per progressBar de waarde laten vullen in de bars 
        */
        baseXpProgressB.setStringPainted(true);
        baseXpProgressB.setValue(0);
        int minimum = 0;
        int base_XP;
        int weight;
        int totaal = weight + height + base_XP;
        int baseXp = (totaal / minimum) *100;
        baseXpProgressB.setValue(baseXP,100);
        
        
        
        
        baseXpProgressB.setValue();
        
        htProgressB.setStringPainted(true);
        htProgressB.setValue(0);
        int minimum = 0;
        int base_XP;
        int weight;
        int totaal = weight + height + base_XP;
        int baseXp = (totaal / minimum) *100;
        htProgressB.setValue(height,100);
        
        htProgressB.setValue();
        
        weightProgressB.setStringPainted(true);
        weightProgressB.setValue(0);
        int minimum = 0;
        int base_XP;
        int weight;
        int totaal = weight + height + base_XP;
        int weight = (totaal / minimum) *100;
        baseXpProgressB.setValue(weight,100);
        
        weightProgressB.setValue();
        
        
    }//GEN-LAST:event_fileOpenerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adviesLabel;
    private javax.swing.JLabel baseNr;
    private javax.swing.JProgressBar baseXpProgressB;
    private javax.swing.JLabel bestandLabel;
    private javax.swing.JButton bladerButton;
    private javax.swing.JButton fileOpener;
    private javax.swing.JTextField filePathField;
    private javax.swing.JLabel heightNr;
    private javax.swing.JProgressBar htPorgressB;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton kiesButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField pokeInput;
    private javax.swing.JLabel pokeOutput;
    private javax.swing.JLabel pokemonLabel;
    private javax.swing.JLabel setAdviesLabel;
    private javax.swing.JLabel setIDLabel;
    private javax.swing.JLabel setNameLabel;
    private javax.swing.JLabel weightNr;
    private javax.swing.JProgressBar weightProgressB;
    // End of variables declaration//GEN-END:variables
}
